services:
  postgres:
    image: postgres:16-alpine
    container_name: fly-away-db
    environment:
      POSTGRES_DB: fly-away
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"